### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by elvijsuntals** [Blowchart/ghost-theme#1]
- [x] remove log in button from code, let's generate it with ghost; only sign up stays hardcoded
- [x] let's also display featured images on single post pages above the headline
- [x] it appears that blowchart logo on top left should lead to blog.blowchart.com not blowchart.com; you can get to blowchart.com by pressing "home", "about" or signup/login buttons
- [x] add favicons:
  need to add this block from blowchart.com to the blog:

```
    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/favicon-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <meta name="msapplication-TileColor" content="#22234e">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
```
- [ ] also, `favicon.ico` file isn't mentioned here, but it should be acessible at `blog.blowchart.com/favicon.ico` as browsers do that by default

**Comment by Ang3r** [comment]
Also static pages (currently only **about** page) aren't responsive

**Comment by no1lov3sme** [comment]
oh, did not catch, that it leads to blowchart.com, sorry

**Comment by elvijsuntals** [comment]
yes, that's OK

**Comment by no1lov3sme** [comment]
`favicon.ico` should be replaced in `ghost/core/shared` path (which is not in this repository), to be accessible at `blog.blowchart.com/favicon.ico`.
